spring:
  profiles:
    active: dev
  datasource:
    hikari:
      idleTimeout: 30000
      maximumPoolSize: 10

caching:
  spring:
    genreListTTL: 14400000

scheduler:
  thread:
    pool:
      size: 5

utils:
  randomMoviesAmount: 3