spring:
  profiles:
    active: dev
  datasource:
    hikari:
      idleTimeout: 30000
      maximumPoolSize: 10
  jpa:
    open-in-view: false

caching:
  spring:
    genreListTTL: 14400000

scheduler:
  thread:
    pool:
      size: 5