spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/movieland?currentSchema=movieland
  jpa:
    open-in-view: false
#    Below two properties are to add to the log sql queries hibernate does.
    show-sql: true
    properties:
      hibernate:
        format_sql: true

caching:
  spring:
    genreListTTL: 14400000

scheduler:
  thread:
    pool:
      size: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"