spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/movieland?currentSchema=movieland
  jpa:
    open-in-view: false
#    Below two properties are to add to the log sql queries hibernate does.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    template:
        default-topic: movietopic-int
    bootstrap:servers: localhost:9092,localhost:9093,localhost:9094
    topic: "movietopic-int"
    producer:
      bootstrap:servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retries: 10
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
        retries: 10
caching:
  spring:
    genreListTTL: 14400000
  movie:
    size: 10
  currency:
    exchangeRatesUrl: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange

scheduler:
  thread:
    pool:
      size: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"